services:
  front:
    build: ./LaForum-Backend
    container_name: LaForum-Backend
  back:
    build: ./LaForum-Frontend
    container_name: LaForum-Frontend
  redis:
    build: ./Redis
    container_name: LaForum-Redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data:
